### ISSUE TITLE
missing -fPIC flag for gcc build on AIX

### ISSUE THREAD

**Issue by Justin-E-Taylor** [numpy/numpy#11317]
I'm getting a numpy error trying to install scipy.  I get the same numpy error trying to install pandas, so I assume the problem is with numpy.  I've tried reinstalling numpy and Python.

IBM i
numpy 1.14.4 (installed via pip3)
Python 3.6.5-1 (installed via yum)

 

-bash-4.3$ pip3 install scipy

Collecting scipy

  Using cached https://files.pythonhosted.org/packages/07/76/7e844757b9f3bf5ab9f951ccd3e4a8eed91ab8720b0aac8c2adcc2fdae9f/scipy-1.1.0.tar.gz

Requirement already satisfied: numpy>=1.8.2 in /QOpenSys/pkgs/lib/python3.6/site-packages (from scipy)

Installing collected packages: scipy

  Running setup.py install for scipy ... error

    Complete output from command /QOpenSys/pkgs/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-c46gpjy8/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mgpugb72-record/install-record.txt --single-version-externally-managed --compile:

 

    Note: if you need reliable uninstall behavior, then install

    with pip instead of using `setup.py install`:

 

      - `pip install .`       (from a git repo or downloaded source

                               release)

      - `pip install scipy`   (last SciPy release on PyPI)

 

 

    Traceback (most recent call last):

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>

        from . import multiarray

    ImportError: Could not load module /QOpenSys/pkgs/lib/python3.6/site-packages/numpy/core/multiarray.so.

        The local-exec model was used for thread-local

           storage, but the module is not the main program.

    Examine the .loader section header with the 'dump -Hv' command.

 

    During handling of the above exception, another exception occurred:

 

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-build-c46gpjy8/scipy/setup.py", line 474, in <module>

        setup_package()

      File "/tmp/pip-build-c46gpjy8/scipy/setup.py", line 450, in setup_package

        from numpy.distutils.core import setup

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>

        from . import add_newdocs

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>

        from numpy.lib import add_newdoc

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>

        from .type_check import *

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>

        import numpy.core.numeric as _nx

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/core/__init__.py", line 26, in <module>

        raise ImportError(msg)

    ImportError:

    Importing the multiarray numpy extension module failed.  Most

    likely you are trying to import a failed build of numpy.

    If you're working with a numpy git repo, try `git clean -xdf` (removes all

    files not under version control).  Otherwise reinstall numpy.

 

    Original error was: Could not load module /QOpenSys/pkgs/lib/python3.6/site-packages/numpy/core/multiarray.so.

        The local-exec model was used for thread-local

           storage, but the module is not the main program.

    Examine the .loader section header with the 'dump -Hv' command.

 

 

    ----------------------------------------

Command "/QOpenSys/pkgs/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-c46gpjy8/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-mgpugb72-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-c46gpjy8/scipy/

**Comment by charris** [comment]
Was it a source or binary install? There have been problems with the source installs on several platforms that should be fixed in the upcoming 1.14.5 release.

**Comment by charris** [comment]
Did the install work with 1.14.3? You can install that version with pip.

**Comment by Justin-E-Taylor** [comment]
I used pip3 to install numpy and attempt scipy & pandas.  I assume that’s a binary package install.
 
I used pip3 to uninstall the default version of numpy and install version 1.14.3.  Like before numpy installed successfully.  I tried scipy again and got the same error (I can post another stacktrace if it helps).
 
FWIW, here’s what I currently have installed:
-bash-4.3$ pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
numpy (1.14.3)
pip (10.0.1)
python-dateutil (2.7.3)
pytz (2018.4)
setuptools (39.2.0)
wheel (0.31.1)

**Comment by mattip** [comment]
Perhaps you may be [lacking the `-fPIC` flag for your compiler](https://stackoverflow.com/questions/31704639/compiling-numpy-for-python3-for-aix-works-but-import-fails), 

You could try to set the CFLAGS by hand:
```
CFLAGS='-fPIC' pip install --upgrade --force-reinstall numpy
```
or by copying the commands from the link above in a git code checkout

**Comment by Justin-E-Taylor** [comment]
The -fPIC flag did make a difference, although I still can't install scipy.  The stacktrace no longer references numpy, so I'm not sure if this is the place to continue this discussion.  

FWIW, here's the new stacktrace and installed Python packages:
`-bash-4.3$ pip3 install scipy

Collecting scipy

  Using cached https://files.pythonhosted.org/packages/07/76/7e844757b9f3bf5ab9f951ccd3e4a8eed91ab8720b0aac8c2adcc2fdae9f/scipy-1.1.0.tar.gz

Installing collected packages: scipy

  Running setup.py install for scipy ... error

    Complete output from command /QOpenSys/pkgs/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0513gqxv/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-63a6i2ou-record/install-record.txt --single-version-externally-managed --compile:

 

    Note: if you need reliable uninstall behavior, then install

    with pip instead of using `setup.py install`:

 

      - `pip install .`       (from a git repo or downloaded source

                               release)

      - `pip install scipy`   (last SciPy release on PyPI)

 

 

    lapack_opt_info:

    lapack_mkl_info:

    customize UnixCCompiler

      libraries mkl_rt not found in ['/QOpenSys/pkgs/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']

      NOT AVAILABLE

 

    openblas_lapack_info:

    customize UnixCCompiler

    customize UnixCCompiler

      libraries openblas not found in ['/QOpenSys/pkgs/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']

      NOT AVAILABLE

 

    openblas_clapack_info:

    customize UnixCCompiler

    customize UnixCCompiler

      libraries openblas,lapack not found in ['/QOpenSys/pkgs/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']

      NOT AVAILABLE

 

    atlas_3_10_threads_info:

    Setting PTATLAS=ATLAS

    customize UnixCCompiler

      libraries tatlas,tatlas not found in /QOpenSys/pkgs/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /QOpenSys/pkgs/lib

   customize UnixCCompiler

      libraries tatlas,tatlas not found in /usr/local/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/local/lib

    customize UnixCCompiler

      libraries tatlas,tatlas not found in /usr/lib64

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib64

    customize UnixCCompiler

      libraries tatlas,tatlas not found in /usr/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib

    customize UnixCCompiler

      libraries tatlas,tatlas not found in /usr/lib/

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib/

    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>

      NOT AVAILABLE

 

    atlas_3_10_info:

    customize UnixCCompiler

      libraries satlas,satlas not found in /QOpenSys/pkgs/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /QOpenSys/pkgs/lib

    customize UnixCCompiler

      libraries satlas,satlas not found in /usr/local/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/local/lib

    customize UnixCCompiler

      libraries satlas,satlas not found in /usr/lib64

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib64

    customize UnixCCompiler

      libraries satlas,satlas not found in /usr/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib

    customize UnixCCompiler

      libraries satlas,satlas not found in /usr/lib/

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib/

    <class 'numpy.distutils.system_info.atlas_3_10_info'>

      NOT AVAILABLE

 

    atlas_threads_info:

    Setting PTATLAS=ATLAS

    customize UnixCCompiler

      libraries ptf77blas,ptcblas,atlas not found in /QOpenSys/pkgs/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /QOpenSys/pkgs/lib

    customize UnixCCompiler

      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/local/lib

    customize UnixCCompiler

      libraries ptf77blas,ptcblas,atlas not found in /usr/lib64

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib64

    customize UnixCCompiler

      libraries ptf77blas,ptcblas,atlas not found in /usr/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib

    customize UnixCCompiler

      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib/

    <class 'numpy.distutils.system_info.atlas_threads_info'>

      NOT AVAILABLE

 

    atlas_info:

    customize UnixCCompiler

      libraries f77blas,cblas,atlas not found in /QOpenSys/pkgs/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /QOpenSys/pkgs/lib

    customize UnixCCompiler

      libraries f77blas,cblas,atlas not found in /usr/local/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/local/lib

    customize UnixCCompiler

      libraries f77blas,cblas,atlas not found in /usr/lib64

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib64

    customize UnixCCompiler

      libraries f77blas,cblas,atlas not found in /usr/lib

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib

    customize UnixCCompiler

      libraries f77blas,cblas,atlas not found in /usr/lib/

    customize UnixCCompiler

      libraries lapack_atlas not found in /usr/lib/

    <class 'numpy.distutils.system_info.atlas_info'>

      NOT AVAILABLE

 

    /QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/system_info.py:624: UserWarning:

        Atlas (http://math-atlas.sourceforge.net/) libraries not found.

        Directories to search for the libraries can be specified in the

        numpy/distutils/site.cfg file (section [atlas]) or by setting

        the ATLAS environment variable.

      self.calc_info()

    lapack_info:

    customize UnixCCompiler

      libraries lapack not found in ['/QOpenSys/pkgs/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']

      NOT AVAILABLE

 

    /QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/system_info.py:624: UserWarning:

        Lapack (http://www.netlib.org/lapack/) libraries not found.

        Directories to search for the libraries can be specified in the

        numpy/distutils/site.cfg file (section [lapack]) or by setting

        the LAPACK environment variable.

      self.calc_info()

    lapack_src_info:

      NOT AVAILABLE

 

    /QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/system_info.py:624: UserWarning:

        Lapack (http://www.netlib.org/lapack/) sources not found.

        Directories to search for the sources can be specified in the

        numpy/distutils/site.cfg file (section [lapack_src]) or by setting

        the LAPACK_SRC environment variable.

      self.calc_info()

      NOT AVAILABLE

 

    Running from scipy source directory.

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-build-0513gqxv/scipy/setup.py", line 474, in <module>

        setup_package()

      File "/tmp/pip-build-0513gqxv/scipy/setup.py", line 470, in setup_package

        setup(**metadata)

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/core.py", line 135, in setup

        config = configuration()

      File "/tmp/pip-build-0513gqxv/scipy/setup.py", line 388, in configuration

        config.add_subpackage('scipy')

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1024, in add_subpackage

        caller_level = 2)

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 993, in get_subpackage

        caller_level = caller_level + 1)

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 930, in _get_configuration_from_setup_py

        config = setup_module.configuration(*args)

      File "scipy/setup.py", line 15, in configuration

        config.add_subpackage('linalg')

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1024, in add_subpackage

        caller_level = 2)

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 993, in get_subpackage

        caller_level = caller_level + 1)

      File "/QOpenSys/pkgs/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 930, in _get_configuration_from_setup_py

        config = setup_module.configuration(*args)

      File "scipy/linalg/setup.py", line 19, in configuration

        raise NotFoundError('no lapack/blas resources found')

    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

 

    ----------------------------------------

Command "/QOpenSys/pkgs/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0513gqxv/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-63a6i2ou-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-0513gqxv/scipy/

 

 

 

 

-bash-4.3$ pip3 list

DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.

freetype-py (1.2.1)

numpy (1.14.5)

pip (10.0.1)

pkg-config (0.0.1)

pypng (0.0.18)

python-dateutil (2.7.3)

pytz (2018.4)

setuptools (39.2.0)

six (1.11.0)

wheel (0.31.1)`


Thanks guys

**Comment by mattip** [comment]
Glad to hear that at least NumPy works now. We use distutil's `customize_compiler` function which digs out the `CCSHARED` key from sysconfig. This would make it seem that your python is misconfigured, what do you get from this? On my platform (`sys.platform == 'linux'`) I get `-fPIC`
```
import sysconfig
print(sysconfig.get_config_var('CCSHARED')
```
What do you get for `sys.platform` ? Perhaps we need to hack in that flag?

**Comment by mattip** [comment]
On the topic of scipy, it [has requirements you need to fulfill](https://scipy.github.io/devdocs/building/linux.html) beyond those of NumPy.

**Comment by Justin-E-Taylor** [comment]
I’m still new to this and (mistakenly) assumed the package manager would take care of the dependencies.  I’ll check out that doc.

Here's that check you asked about.  This page messes with the formating, but the sysconfig.get_config returned a blank line.
`-bash-4.3$ python3
Python 3.6.5 (default, Apr 26 2018, 15:03:33)
[GCC 6.3.0] on aix6
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> print(sysconfig.get_config_var('CCSHARED'))
 
>>> import sys
>>> sys.platform
'aix6'
>>>  `

**Comment by mattip** [comment]
So that seems like a problem, IMO we should always be building with `-fPIC`, even if python itself is not built with it.

BTW, you need to use a code block which is three backticks to get the formatting to work (without the `>`)
```
> ```
> Here is my code
> ```
```

**Comment by Justin-E-Taylor** [comment]
I checked the dependencies in the link above.  I'm missing some of them and those packages don't seem to be available for my  server OS.  I also checked my laptop, which has a working scipy.  It's also missing some of listed dependencies.  I'm not sure what that means.

```
I've been using the toolbar button to try and mark code blocks.  
The triple back tics work.  
Thanks
```

**Comment by mattip** [comment]
You may find `ldd path/to/scipy/linalg/_flinalg*.so` helpful to see what your working scipy uses, but you will have to take it up with SciPy. 

We should try to stick with whether our build scripts should force `-fPIC` on all gcc platforms, and not depend on that flag to come from python's sysconfig module

**Comment by Justin-E-Taylor** [comment]
I think I have all I need from this thread.  Is there anything I can do to help you?

**Comment by rgommers** [comment]
Thanks @Justin-E-Taylor and @mattip, I think this is resolved. And is a duplicate of gh-14488, see https://github.com/numpy/numpy/issues/14488#issuecomment-533850653 for more context.
