### ISSUE TITLE
CI: OpenBLAS CI failing

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy#25849]
Currently all CI jobs are failing with the following error during dependency installation:

```
2024-02-18T17:22:09.9124418Z Installing collected packages: ninja, pyproject_hooks, packaging, meson, Cython, click, spin, pyproject-metadata, build, meson-python
2024-02-18T17:22:11.3721139Z Successfully installed Cython-3.0.8 build-1.0.3 click-8.1.7 meson-1.3.2 meson-python-0.15.0 ninja-1.11.1.1 packaging-23.2 pyproject-metadata-0.7.1 pyproject_hooks-1.0.0 spin-0.8
2024-02-18T17:22:11.9544623Z Looking in indexes: https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
2024-02-18T17:22:12.1456855Z ERROR: Could not find a version that satisfies the requirement scipy-openblas32 (from versions: none)
2024-02-18T17:22:12.1458454Z ERROR: No matching distribution found for scipy-openblas32
2024-02-18T17:22:12.2403271Z ##[error]Process completed with exit code 1.

```

**Comment by mattip** [comment]
I think the project name (with a dash) is cursed. I can install from https://pypi.anaconda.org/multibuild-wheels-staging/simple, where the scipy-openblas32 wheel zip files have an `_` in the name, but not from https://pypi.anaconda.org/scientific-python-nightly-wheels/simple where they have a `-` in the name.

Looking at a successful workflow, [the file downloaded](https://github.com/numpy/numpy/actions/runs/7945606976/job/21692459207#step:4:60) had a `_`. I wonder if somehow anaconda normalized the filenames improperly and broke the download?

**Comment by matthewfeickert** [comment]
Can you check the metadata for the wheels? c.f. https://github.com/scientific-python/upload-nightly-action/issues/65#issuecomment-1951513302 for why I think this is relevant.

**Comment by matthewfeickert** [comment]
c.f. https://github.com/MacPython/openblas-libs/pull/140

**Comment by rgommers** [comment]
I see this is being worked on already, but for completeness: Windows wheel builds are broken due to this; on other OSes things seem to work: [wheel builder CI log](https://github.com/numpy/numpy/actions/runs/7956120566/job/21716241016).

**Comment by matthewfeickert** [comment]
> I see this is being worked on already, but for completeness: Windows wheel builds are broken due to this; on other OSes things seem to work: [wheel builder CI log](https://github.com/numpy/numpy/actions/runs/7956120566/job/21716241016).

@rgommers I'm going to believe you as you obviously know the project better than me, but where in the

https://github.com/numpy/numpy/blob/441c9e600be16e1619ef6fb04e7ecdf6a12069cc/.github/workflows/wheels.yml#L59

are the `scipy-openblas` wheels used? The log shows more than `scipy-openblas` missing

```
  
  Library m found: NO
  Fetching value of define "__MINGW32__" :  
  found pkg-config 'C:\\Strawberry\\perl\\bin\\pkg-config.BAT' but it is Strawberry Perl and thus broken. Ignoring...
  Found Pkg-config: NO
  Run-time dependency scipy-openblas found: NO (tried pkgconfig)
  Run-time dependency mkl found: NO (tried pkgconfig and system)
  Run-time dependency mkl found: NO (tried pkgconfig and system)
  Found CMake: C:\Program Files\CMake\bin\cmake.EXE (3.27.9)
  WARNING: CMake Toolchain: Failed to determine CMake compilers state
  Run-time dependency openblas found: NO (tried pkgconfig, pkgconfig, pkgconfig, system and cmake)
  Run-time dependency flexiblas found: NO (tried pkgconfig and cmake)
  Run-time dependency blis found: NO (tried pkgconfig and cmake)
  Run-time dependency blas found: NO (tried pkgconfig and system)
  
  ..\numpy\meson.build:185:4: ERROR: Problem encountered: No BLAS library detected! Install one, or use the `allow-noblas` build option (note, this may be up to 100x slower for some linear algebra operations).
  
  A full log can be found at D:\a\numpy\numpy\build\meson-logs\meson-log.txt
  
  ERROR Backend subprocess exited when trying to invoke build_wheel
```

What I show in https://github.com/scientific-python/upload-nightly-action/issues/65#issuecomment-1951735277 is that this is a systematic issue due to the wheel names being manually changed, so this should not be OS dependent.

**Comment by rgommers** [comment]
Here's an example from the [manylinux cp311 log](https://github.com/numpy/numpy/actions/runs/7956120566/job/21716238679):
```
# In the before_build phase:
Installing collected packages: scipy-openblas64, scipy-openblas32, click, spin

# In the "Building wheel" phase:
  Run-time dependency scipy-openblas found: YES 0.3.26
  Message: BLAS symbol suffix: 64_
```

`cibuildwheel` config is hard to navigate, but you're not quite looking at the right file. The "before build" phase is: https://github.com/numpy/numpy/blob/main/tools/wheels/cibw_before_build.sh#L30

Config files for the different phase can be found from https://github.com/numpy/numpy/blob/main/pyproject.toml#L140.

**Comment by matthewfeickert** [comment]
Thanks @rgommers. Though what I should have asked is where are the `scientific-python-nightly-wheels` package index nightly wheels for `scipy-openblas64` and `scipy-openblas32` used, as referenced in https://github.com/numpy/numpy/issues/25849#issue-2141107837?

In the "before build phase" bit that you linked me

https://github.com/numpy/numpy/blob/441c9e600be16e1619ef6fb04e7ecdf6a12069cc/tools/wheels/cibw_before_build.sh#L30-L36

the wheels being installed in `requirements/ci_requirements.txt`

https://github.com/numpy/numpy/blob/441c9e600be16e1619ef6fb04e7ecdf6a12069cc/requirements/ci_requirements.txt#L3-L4

are being installed [from PyPI](https://pypi.org/project/scipy-openblas64/0.3.26.0.4/#files), not https://anaconda.org/scientific-python-nightly-wheels/ .

**Comment by rgommers** [comment]
Oh sorry, I misunderstood that. Yes, for numpy wheel builds the `scipy-openblas` wheels should be coming from PyPI. But that's also true for most regular CI jobs; the only one installing from the Anaconda bucket is the one with `$USE_NIGHTLY_OPENBLAS == "true"` in `.github/workflows/linux_blas.yml`.

**Comment by matthewfeickert** [comment]
Right. And (repeating things here for posterity) the `true` matrix job

https://github.com/numpy/numpy/blob/441c9e600be16e1619ef6fb04e7ecdf6a12069cc/.github/workflows/linux_blas.yml#L60-L61

https://github.com/numpy/numpy/blob/441c9e600be16e1619ef6fb04e7ecdf6a12069cc/.github/workflows/linux_blas.yml#L74-L79

failing due to filename errors on `scientific-python-nightly-wheels` index is what @ngoldbaum is reporting in https://github.com/numpy/numpy/issues/25849#issue-2141107837, so given the errors in the logs (https://github.com/numpy/numpy/issues/25849#issuecomment-1952672130) I think what you're reporting in https://github.com/numpy/numpy/issues/25849#issuecomment-1951991742 is a different problem.

Am I missing something more about the [`.github/workflows/wheels.yml`](https://github.com/numpy/numpy/blob/441c9e600be16e1619ef6fb04e7ecdf6a12069cc/.github/workflows/wheels.yml) workflow?

**Comment by andyfaff** [comment]
> I see this is being worked on already, but for completeness: Windows wheel builds are broken due to this; on other OSes things seem to work: [wheel builder CI log](https://github.com/numpy/numpy/actions/runs/7956120566/job/21716241016).

I think the windows wheels builds have a problem with the [installed pkg-config](https://github.com/numpy/numpy/actions/runs/7956120566/job/21716241016#step:6:352), meson is not coming up with a useful pkg-config version.
The reason for this is in an earlier step where [pkgconfiglite is not being installed](https://github.com/numpy/numpy/actions/runs/7956120566/job/21716241016#step:4:22).

For the wheels build this needs to be working before anything else is investigated.

**Comment by rgommers** [comment]
Good catch. Always fun when a tool fails to install something but then that doesn't actually propagate exit codes to fail the CI job.

**Comment by ngoldbaum** [comment]
Created #25863 to track the issues with windows wheel builds.

**Comment by matthewfeickert** [comment]
This is now fixed. c.f. https://github.com/MacPython/openblas-libs/pull/140#issuecomment-1958049769

**Comment by matthewfeickert** [comment]
...though I will note one thing that is confusing to me following the `v0.3.26.0.5` upload to https://anaconda.org/scientific-python-nightly-wheels/scipy-openblas32: Installing from the index is finding wheels for `0.3.26.199` as `pip` views that as more recent than `0.3.26.0.5`
```console
$ docker run --rm -ti python:3.11 /bin/bash
root@2e015a4ce2b4:/# python -m venv venv && . venv/bin/activate
(venv) root@2e015a4ce2b4:/# python -m pip --quiet install --upgrade pip
(venv) root@2e015a4ce2b4:/# python -m pip install --index-url https://pypi.anaconda.org/scikit-hep-nightly-wheels/simple scipy-openblas32
Looking in indexes: https://pypi.anaconda.org/scikit-hep-nightly-wheels/simple
Collecting scipy-openblas32
  Downloading https://pypi.anaconda.org/scikit-hep-nightly-wheels/simple/scipy-openblas32/0.3.26.199/scipy_openblas32-0.3.26.199-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 2.5 MB/s eta 0:00:00
Installing collected packages: scipy-openblas32
Successfully installed scipy-openblas32-0.3.26.199
(venv) root@2e015a4ce2b4:/#
```

but I'm not sure where this `0.3.26.199` is coming from as this file doesn't exist on the index

![image](https://github.com/numpy/numpy/assets/5142394/bffabf01-d046-4ecc-93bc-e9adbc69d27e)

```console
$ curl --silent https://api.anaconda.org/package/scientific-python-nightly-wheels/scipy-openblas32 | jq '.latest_version'
"0.3.26.199"
$ curl --silent https://api.anaconda.org/release/scientific-python-nightly-wheels/scipy-openblas32/0.3.26.199 | grep 'scipy_openblas32'  # nothing with an '_' in the name
$ curl --silent https://api.anaconda.org/release/scientific-python-nightly-wheels/scipy-openblas32/0.3.26.199 | jq '.[][0].basename'  # matches the expected view on the web
"scipy-openblas32-0.3.26.199-py3-none-macosx_10_9_x86_64.whl"
$ curl --silent https://api.anaconda.org/release/scientific-python-nightly-wheels/scipy-openblas32/0.3.26.0.5 | jq '.[][0].basename'  # and the wheels just uploaded for 0.3.26.0.5 to show we're filtering okay
"scipy_openblas32-0.3.26.0.5-py3-none-macosx_10_9_x86_64.whl"
```

So that's kinda weird!

**Comment by matthewfeickert** [comment]
@mattip As the wheels are `0.3.26.0.5` with `pip` locally I think(?) this has to come down to how `pip` does version resolution. As the latest release of [`scipy-openblas32` on PyPI is `0.3.26.0.4`](https://pypi.org/project/scipy-openblas32/0.3.26.0.4/) can you comment on if the `0.3.26.184`, `0.3.26.186`, and `0.3.26.199` releases on https://anaconda.org/scientific-python-nightly-wheels/scipy-openblas32 are still needed? If not, we could remove them and then I think the `0.3.26.0.5` and following versions would get picked up (?).

That said, maybe not given

```console
(venv) root@2e015a4ce2b4:/# python -m pip install --upgrade --index-url https://pypi.anaconda.org/scikit-hep-nightly-wheels/simple 'scipy-openblas32==0.3.26.0.5'
Looking in indexes: https://pypi.anaconda.org/scikit-hep-nightly-wheels/simple
ERROR: Could not find a version that satisfies the requirement scipy-openblas32==0.3.26.0.5 (from versions: 0.3.26.199)
ERROR: No matching distribution found for scipy-openblas32==0.3.26.0.5
```

I don't understand enough about how Anaconda Cloud works to know if this is expected or not.

cc @kenodegard @dholth (Can you please put us in touch with the right teams at Anaconda?)

**Comment by matthewfeickert** [comment]
@ngoldbaum can you please reopen this if the `0.3.26.199` wheels fail in the next run of the CI?

**Comment by mattip** [comment]
Let's leave this open. 

The "199" version is the latest nightly, which is the whole point of the scientific-python-nightly-wheels storage site. It is the actual wheel we would like to download from anaconda, to fix this issue. The non-nightly builds (like the one from #140) are for uploading to PyPI.

The CI will still fail on the nightly build, since the URL https://anaconda.org/scientific-python-nightly-wheels/simple still does not work, even after #140:
```
$ pip install -i https://anaconda.org/scientific-python-nightly-wheels/simple "scipy-openblas32"                                      
Looking in indexes: https://anaconda.org/scientific-python-nightly-wheels/simple                                                                                             
ERROR: Could not find a version that satisfies the requirement scipy-openblas32 (from versions: none)                                                                  
ERROR: No matching distribution found for scipy-openblas32
```

**Comment by matthewfeickert** [comment]
> The "199" version is the latest nightly, which is the whole point of the scientific-python-nightly-wheels storage site. It is the actual wheel we would like to download from anaconda, to fix this issue.

@mattip Ah great! I didn't know that the nightlies had the "newer" version numbers &mdash; I assumed (wrongly) they would have vcs information in their names. Can you you please trigger a manual build of the nightly workflow now then?

**Comment by mattip** [comment]
Sure, I will trigger a build. But I don't understand why the wheel uploaded from #140 is not available from the upload site. It seems something is still off with either anaconda-cloud or the wheel.

**Comment by matthewfeickert** [comment]
> Sure, I will trigger a build. But I don't understand why the wheel uploaded from #140 is not available from the upload site. It seems something is still off with either anaconda-cloud or the wheel.

Yes, I summarize my confusion in https://github.com/numpy/numpy/issues/25849#issuecomment-1958177438 on this.

**Comment by mattip** [comment]
@matthewfeickert let's continue the conversation on MacPython/openblas-libs#139 to keep the noise down for the 600 people watching this repo.

**Comment by matthewfeickert** [comment]
@mattip Thanks. The triggering of the nightly build has things working now:

```console
$ docker run --rm -ti python:3.11 /bin/bash
root@55e702e009ea:/# python -m venv venv && . venv/bin/activate
(venv) root@55e702e009ea:/# python -m pip install --index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple scipy-openblas32
Looking in indexes: https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
Collecting scipy-openblas32
  Downloading https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/scipy-openblas32/0.3.26.201/scipy_openblas32-0.3.26.201-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 2.2 MB/s eta 0:00:00
Installing collected packages: scipy-openblas32
Successfully installed scipy-openblas32-0.3.26.201
(venv) root@55e702e009ea:/# python -m pip install --index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple scipy-openblas64
Looking in indexes: https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
Collecting scipy-openblas64
  Downloading https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/scipy-openblas64/0.3.26.201/scipy_openblas64-0.3.26.201-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.2/11.2 MB 1.7 MB/s eta 0:00:00
Installing collected packages: scipy-openblas64
Successfully installed scipy-openblas64-0.3.26.201
(venv) root@55e702e009ea:/# python -m pip list
Package          Version
---------------- ----------
pip              24.0
scipy-openblas32 0.3.26.201
scipy-openblas64 0.3.26.201
setuptools       65.5.0
(venv) root@55e702e009ea:/#
```

**Comment by mattip** [comment]
Cool. Reclosing. Thanks for the help.
