### ISSUE TITLE
TYP: pylint `--prefer-stubs` leads to many errors

### ISSUE THREAD

**Issue by furgerf** [numpy/numpy#27244]
### Describe the issue:

(Not sure this is the right place/way to report this - sorry in advance if it isn't.)

[Pylint 3.2.1 introduced `--prefer-stubs`](https://pylint.readthedocs.io/en/stable/whatsnew/3/3.2/index.html#what-s-new-in-pylint-3-2-1), but using this leads to many errors related to typing around ndarray.

### Reproduce the code example:

```python
import numpy as np
import numpy.typing as npt

Float64NDArray = npt.NDArray[np.float64]
```

### Error message:

```shell
E1136: Value 'npt.NDArray' is unsubscriptable (unsubscriptable-object)
```

### Python and NumPy Versions:

numpy 1.26.4
Python 3.11.2 (main, Feb  9 2023, 05:12:33) [GCC 10.2.1 20210110]

### Type-checker version and settings:

pylint 3.2.6
astroid 3.2.4

**Comment by jorenham** [comment]
Thanks for raising this @furgerf, this is indeed the correct way of reporting such issues.

My guess is that this might've been caused by the lack of `typing.TypeAlias` annotations for the `numpy.typing.NDArray` alias in numpy 1.26.4. This has been solved in numpy 2.1.

So could you check if this is still an issue with numpy 2.1?

**Comment by furgerf** [comment]
Cool, thanks for the reply. Unfortunately, I'm still getting the same result with numpy 2.1.0.

That was just a simple example for one of the issues I encountered. Maybe some more examples would be useful:

- I also get `E1136: Value 'np.arange(12)' is unsubscriptable (unsubscriptable-object)`for `np.arange(12)[0]`.
- I get `E1133: Non-iterable value np.split(np.arange(12), 3) is used in an iterating context (not-an-iterable)` for `[val for val in np.split(np.arange(12), 3)]`
- Similarly, `E1133: Non-iterable value np.diff(np.arange(12)) is used in an iterating context (not-an-iterable)` for `[val for val in np.diff(np.arange(12))]`

**Comment by jorenham** [comment]
Could you post the code that lead to these errors? Then I could have a look it at too

**Comment by furgerf** [comment]
Sure, full input (file):

```python
import numpy as np
import numpy.typing as npt

Float64NDArray = npt.NDArray[np.float64]

_ = [val for val in np.split(np.arange(12), 3)]

_ = [val for val in np.diff(np.arange(12))]

_ = np.arange(12)[0]
```

Full output:
```
************* Module foo
foo.py:1:0: C0104: Disallowed name "foo" (disallowed-name)
foo.py:4:17: E1136: Value 'npt.NDArray' is unsubscriptable (unsubscriptable-object)
foo.py:6:20: E1133: Non-iterable value np.split(np.arange(12), 3) is used in an iterating context (not-an-iterable)
foo.py:6:4: R1721: Unnecessary use of a comprehension, use list(np.split(np.arange(12), 3)) instead. (unnecessary-comprehension)
foo.py:8:20: E1133: Non-iterable value np.diff(np.arange(12)) is used in an iterating context (not-an-iterable)
foo.py:8:4: R1721: Unnecessary use of a comprehension, use list(np.diff(np.arange(12))) instead. (unnecessary-comprehension)
foo.py:10:4: E1136: Value 'np.arange(12)' is unsubscriptable (unsubscriptable-object)
```

**Comment by jorenham** [comment]
I reproduced this issue with `numpy==2.1` and `pylint==3.2.6"`:

When I run it as `pylint issue_27244.py` I get:

```
************* Module issue_27244
issue_27244.py:1:0: C0114: Missing module docstring (missing-module-docstring)
issue_27244.py:6:4: R1721: Unnecessary use of a comprehension, use list(np.split(np.arange(12), 3)) instead. (unnecessary-comprehension)
issue_27244.py:8:4: R1721: Unnecessary use of a comprehension, use list(np.diff(np.arange(12))) instead. (unnecessary-comprehension)

------------------------------------------------------------------
Your code has been rated at 5.00/10 (previous run: 0.00/10, +5.00)
```

And `pylint --prefer-stubs yes issue_27244.py` gives:

```
************* Module issue_27244
issue_27244.py:1:0: C0114: Missing module docstring (missing-module-docstring)
issue_27244.py:4:17: E1136: Value 'npt.NDArray' is unsubscriptable (unsubscriptable-object)
issue_27244.py:6:20: E1133: Non-iterable value np.split(np.arange(12), 3) is used in an iterating context (not-an-iterable)
issue_27244.py:6:4: R1721: Unnecessary use of a comprehension, use list(np.split(np.arange(12), 3)) instead. (unnecessary-comprehension)
issue_27244.py:8:20: E1133: Non-iterable value np.diff(np.arange(12)) is used in an iterating context (not-an-iterable)
issue_27244.py:8:4: R1721: Unnecessary use of a comprehension, use list(np.diff(np.arange(12))) instead. (unnecessary-comprehension)
issue_27244.py:10:4: E1136: Value 'np.arange(12)' is unsubscriptable (unsubscriptable-object)
```

---

But, when I replace 

```python
Float64NDArray = npt.NDArray[np.float64]
```

with

```python
Float64NDArray = np.ndarray[Any, np.dtype[np.float64]]
```

`pylint --prefer-stubs yes issue_27244.py` gives:

```
************* Module issue_27244
issue_27244.py:1:0: C0114: Missing module docstring (missing-module-docstring)
issue_27244.py:5:20: E1133: Non-iterable value np.split(np.arange(12), 3) is used in an iterating context (not-an-iterable)
issue_27244.py:5:4: R1721: Unnecessary use of a comprehension, use list(np.split(np.arange(12), 3)) instead. (unnecessary-comprehension)
issue_27244.py:7:20: E1133: Non-iterable value np.diff(np.arange(12)) is used in an iterating context (not-an-iterable)
issue_27244.py:7:4: R1721: Unnecessary use of a comprehension, use list(np.diff(np.arange(12))) instead. (unnecessary-comprehension)
issue_27244.py:9:4: E1136: Value 'np.arange(12)' is unsubscriptable (unsubscriptable-object)
```

So the `NDArray` error has gone now.

---

Because `numpy.typing.NDArray` is defined (only) in a `.py` file, which doesn't have a corresponding `.pyi` (as there's no need for it), I think it's safe to conclude that `pylint --prefer-stubs` **only** looks at the stubs, and breaks down when there aren't any.

So this could be an issue with `pylint`, or perhaps expected behavior, but either way, I don't think that this is a numpy issue. As far as I'm concerned, there's nothing wrong with the current [`numpy.typing.NDArray`](https://github.com/numpy/numpy/blob/v2.1.0/numpy/_typing/_array_like.py) definition.

---

Is there any particular reason for you to you `--prefer_stubs`?

**Comment by furgerf** [comment]
> Because numpy.typing.NDArray is defined (only) in a .py file, which doesn't have a corresponding .pyi (as there's no need for it), I think it's safe to conclude that pylint --prefer-stubs only looks at the stubs, and breaks down when there aren't any.
> 
> So this could be an issue with pylint, or perhaps expected behavior, but either way, I don't think that this is a numpy issue. As far as I'm concerned, there's nothing wrong with the current [numpy.typing.NDArray](https://github.com/numpy/numpy/blob/v2.1.0/numpy/_typing/_array_like.py?rgh-link-date=2024-08-20T16%3A02%3A19Z) definition.

Thanks, yes that makes sense, I filed https://github.com/pylint-dev/pylint/issues/9889 to ask about it.

There are quite some additional issues, that aren't (directly) related to NDArray, like the `not-an-iterable` from `np.diff`. However, that's something [their docs](https://pylint.pycqa.org/en/latest/user_guide/configuration/all-options.html#prefer-stubs) state as a possibility. So maybe a better example would be `np.arange(12)[0]`, which returns `Value 'np.arange(12)' is unsubscriptable (unsubscriptable-object)`. Do you have an idea how those come about?

> Is there any particular reason for you to you --prefer_stubs?

Yes, I've had trouble with linting code that uses protobuf generated files - [this solution](https://github.com/protocolbuffers/protobuf/issues/10372#issuecomment-2270856942) has worked for me as well, but led to the numpy issues, as I found out later...

**Comment by jorenham** [comment]
> So maybe a better example would be `np.arange(12)[0]`, which returns `Value 'np.arange(12)' is unsubscriptable (unsubscriptable-object)`. Do you have an idea how those come about?

`np.arange` is annotated to return `npt.NDArray`: https://github.com/numpy/numpy/blob/v2.1.0/numpy/_core/multiarray.pyi#L765-L864

But https://github.com/numpy/numpy/pull/27177/files that aims to change this.

> > Is there any particular reason for you to you --prefer_stubs?
> 
> Yes, I've had trouble with linting code that uses protobuf generated files - [this solution](https://github.com/protocolbuffers/protobuf/issues/10372#issuecomment-2270856942) has worked for me as well, but led to the numpy issues, as I found out later...

Ah that seems annoying... 
I see that the issue is open since 2022, so you might want to consider submitting a PR to fix it yourself 🤷🏻

**Comment by jorenham** [comment]
@furgerf is it OK if I close this issue?

**Comment by furgerf** [comment]
> @furgerf is it OK if I close this issue?

I think so, yes - thank you for your time!
