### ISSUE TITLE
BUG: numpy build internal compiler error: Segmentation fault on s390x OS

### ISSUE THREAD

**Issue by Ganeshkumhar1** [numpy/numpy#27699]
### Describe the issue:

I am ubale to build numpy on s390x host. I tried building numpy 2.0.1 and 2.1.3, both build ran into same compilation errors.

### Reproduce the code example:

```python
python -m build --wheel —no-isolation .
```

### Error message:

```shell
bash-4.4$ python -m build --wheel —no-isolation .
* Getting build dependencies for wheel...
* Building wheel...
+ /home/user/python/bin/python /home/user/numpy/2.0.1/numpy-2.0.1/vendored-meson/meson/meson.py setup /home/user/numpy/2.0.1/numpy-2.0.1 /home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-id1eqrop -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-id1eqrop/meson-python-native-file.ini
The Meson build system
Version: 1.4.99
Source dir: /home/user/numpy/2.0.1/numpy-2.0.1
Build dir: /home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-id1eqrop
Build type: native build
Project name: NumPy
Project version: 2.0.1
C compiler for the host machine: gcc (gcc 8.4.1 "gcc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)")
C linker for the host machine: gcc ld.bfd 2.30-93
C++ compiler for the host machine: g++ (gcc 8.4.1 "g++ (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)")
C++ linker for the host machine: g++ ld.bfd 2.30-93
Cython compiler for the host machine: cython (cython 3.0.10)
Host machine cpu family: s390x
Host machine cpu: s390x
Program python found: YES (/home/user/python/bin/python)
Found pkg-config: YES (/bin/pkg-config) 1.4.2
Run-time dependency python found: YES 3.12
Has header "Python.h" with dependency python-3.12: YES
Compiler for C supports arguments -fno-strict-aliasing: YES
Message: During parsing cpu-dispatch: The following CPU features were ignored due to platform incompatibility or lack of support:
"XOP FMA4"
Test features "VX" : Supported
Test features "VXE" : Supported
Test features "VXE2" : Unsupported due to Arguments "-mzvector, -march=arch13" are not supported
Configuring npy_cpu_dispatch_config.h using configuration
Message:
CPU Optimization Options
  baseline:
    Requested : min
    Enabled   :
  dispatch:
    Requested : max -xop -fma4
    Enabled   : VX VXE

Library m found: YES
Run-time dependency scipy-openblas found: NO (tried pkgconfig)
Run-time dependency openblas found: YES 0.3.27
Message: BLAS symbol suffix:
Run-time dependency openblas found: YES 0.3.27
Program _build_utils/process_src_template.py found: YES (/home/user/python/bin/python /home/user/numpy/2.0.1/numpy-2.0.1/numpy/_build_utils/process_src_template.py)
Program _build_utils/tempita.py found: YES (/home/user/python/bin/python /home/user/numpy/2.0.1/numpy-2.0.1/numpy/_build_utils/tempita.py)
Configuring __config__.py using configuration
Checking for size of "short" : 2
Checking for size of "int" : 4
Checking for size of "long" : 8
Checking for size of "long long" : 8
Checking for size of "float" : 4
Checking for size of "double" : 8
Checking for size of "long double" : 16
Checking for size of "size_t" : 8
Checking for size of "size_t" : 8 (cached)
Checking for size of "wchar_t" : 4
Checking for size of "off_t" : 8
Checking for size of "Py_intptr_t" with dependency python-3.12: 8
Checking for size of "PY_LONG_LONG" with dependency python-3.12: 8
Has header "complex.h" : YES
Checking for type "complex float" : YES
Checking for size of "complex float" : 8
Checking for type "complex double" : YES
Checking for size of "complex double" : 16
Checking for type "complex long double" : YES
Checking for size of "complex long double" : 32
Checking for function "sin" with dependency -lm: YES
Checking for function "cos" with dependency -lm: YES
Checking for function "tan" with dependency -lm: YES
Checking for function "sinh" with dependency -lm: YES
Checking for function "cosh" with dependency -lm: YES
Checking for function "tanh" with dependency -lm: YES
Checking for function "fabs" with dependency -lm: YES
Checking for function "floor" with dependency -lm: YES
Checking for function "ceil" with dependency -lm: YES
Checking for function "sqrt" with dependency -lm: YES
Checking for function "log10" with dependency -lm: YES
Checking for function "log" with dependency -lm: YES
Checking for function "exp" with dependency -lm: YES
Checking for function "asin" with dependency -lm: YES
Checking for function "acos" with dependency -lm: YES
Checking for function "atan" with dependency -lm: YES
Checking for function "fmod" with dependency -lm: YES
Checking for function "modf" with dependency -lm: YES
Checking for function "frexp" with dependency -lm: YES
Checking for function "ldexp" with dependency -lm: YES
Checking for function "expm1" with dependency -lm: YES
Checking for function "log1p" with dependency -lm: YES
Checking for function "acosh" with dependency -lm: YES
Checking for function "asinh" with dependency -lm: YES
Checking for function "atanh" with dependency -lm: YES
Checking for function "rint" with dependency -lm: YES
Checking for function "trunc" with dependency -lm: YES
Checking for function "exp2" with dependency -lm: YES
Checking for function "copysign" with dependency -lm: YES
Checking for function "nextafter" with dependency -lm: YES
Checking for function "cbrt" with dependency -lm: YES
Checking for function "log2" with dependency -lm: YES
Checking for function "pow" with dependency -lm: YES
Checking for function "hypot" with dependency -lm: YES
Checking for function "atan2" with dependency -lm: YES
Checking for function "csin" with dependency -lm: YES
Checking for function "csinh" with dependency -lm: YES
Checking for function "ccos" with dependency -lm: YES
Checking for function "ccosh" with dependency -lm: YES
Checking for function "ctan" with dependency -lm: YES
Checking for function "ctanh" with dependency -lm: YES
Checking for function "creal" with dependency -lm: YES
Checking for function "cimag" with dependency -lm: YES
Checking for function "conj" with dependency -lm: YES
Checking for function "strtoll" : YES
Checking for function "strtoull" : YES
Checking for function "cabs" with dependency -lm: YES
Checking for function "cabsf" with dependency -lm: YES
Checking for function "cabsl" with dependency -lm: YES
Checking for function "cacos" with dependency -lm: YES
Checking for function "cacosf" with dependency -lm: YES
Checking for function "cacosl" with dependency -lm: YES
Checking for function "cacosh" with dependency -lm: YES
Checking for function "cacoshf" with dependency -lm: YES
Checking for function "cacoshl" with dependency -lm: YES
Checking for function "carg" with dependency -lm: YES
Checking for function "cargf" with dependency -lm: YES
Checking for function "cargl" with dependency -lm: YES
Checking for function "casin" with dependency -lm: YES
Checking for function "casinf" with dependency -lm: YES
Checking for function "casinl" with dependency -lm: YES
Checking for function "casinh" with dependency -lm: YES
Checking for function "casinhf" with dependency -lm: YES
Checking for function "casinhl" with dependency -lm: YES
Checking for function "catan" with dependency -lm: YES
Checking for function "catanf" with dependency -lm: YES
Checking for function "catanl" with dependency -lm: YES
Checking for function "catanh" with dependency -lm: YES
Checking for function "catanhf" with dependency -lm: YES
Checking for function "catanhl" with dependency -lm: YES
Checking for function "cexp" with dependency -lm: YES
Checking for function "cexpf" with dependency -lm: YES
Checking for function "cexpl" with dependency -lm: YES
Checking for function "clog" with dependency -lm: YES
Checking for function "clogf" with dependency -lm: YES
Checking for function "clogl" with dependency -lm: YES
Checking for function "cpow" with dependency -lm: YES
Checking for function "cpowf" with dependency -lm: YES
Checking for function "cpowl" with dependency -lm: YES
Checking for function "csqrt" with dependency -lm: YES
Checking for function "csqrtf" with dependency -lm: YES
Checking for function "csqrtl" with dependency -lm: YES
Checking for function "csin" with dependency -lm: YES (cached)
Checking for function "csinf" with dependency -lm: YES
Checking for function "csinl" with dependency -lm: YES
Checking for function "csinh" with dependency -lm: YES (cached)
Checking for function "csinhf" with dependency -lm: YES
Checking for function "csinhl" with dependency -lm: YES
Checking for function "ccos" with dependency -lm: YES (cached)
Checking for function "ccosf" with dependency -lm: YES
Checking for function "ccosl" with dependency -lm: YES
Checking for function "ccosh" with dependency -lm: YES (cached)
Checking for function "ccoshf" with dependency -lm: YES
Checking for function "ccoshl" with dependency -lm: YES
Checking for function "ctan" with dependency -lm: YES (cached)
Checking for function "ctanf" with dependency -lm: YES
Checking for function "ctanl" with dependency -lm: YES
Checking for function "ctanh" with dependency -lm: YES (cached)
Checking for function "ctanhf" with dependency -lm: YES
Checking for function "ctanhl" with dependency -lm: YES
Checking for function "isfinite" with dependency -lm: YES
Header "Python.h" has symbol "isfinite" with dependency python-3.12: YES
Checking for function "isinf" with dependency -lm: YES
Header "Python.h" has symbol "isinf" with dependency python-3.12: YES
Checking for function "isnan" with dependency -lm: YES
Header "Python.h" has symbol "isnan" with dependency python-3.12: YES
Checking for function "signbit" with dependency -lm: YES
Header "Python.h" has symbol "signbit" with dependency python-3.12: YES
Checking for function "fallocate" : YES
Header "Python.h" has symbol "HAVE_FTELLO" with dependency python-3.12: YES
Header "Python.h" has symbol "HAVE_FSEEKO" with dependency python-3.12: YES
Checking for function "backtrace" : YES
Checking for function "madvise" : YES
Has header "features.h" : YES
Has header "xlocale.h" : NO
Has header "dlfcn.h" : YES
Has header "execinfo.h" : YES
Has header "libunwind.h" : NO
Has header "sys/mman.h" : YES
Checking for function "strtold_l" : YES
Compiler for C supports arguments -O3: YES
Has header "endian.h" : YES
Has header "sys/endian.h" : NO
Compiler for C supports function attribute visibility:hidden: YES
Configuring config.h using configuration
Configuring _numpyconfig.h using configuration
Configuring npymath.ini using configuration
Configuring mlib.ini using configuration
Configuring numpy.pc using configuration
Generating multi-targets for "_umath_tests.dispatch.h"
  Enabled targets: VXE, VX, baseline
Generating multi-targets for "argfunc.dispatch.h"
  Enabled targets: VXE, VX, baseline
Generating multi-targets for "x86_simd_argsort.dispatch.h"
  Enabled targets:
Generating multi-targets for "x86_simd_qsort.dispatch.h"
  Enabled targets:
Generating multi-targets for "x86_simd_qsort_16bit.dispatch.h"
  Enabled targets:
Generating multi-targets for "highway_qsort.dispatch.h"
  Enabled targets:
Generating multi-targets for "highway_qsort_16bit.dispatch.h"
  Enabled targets:
Generating multi-targets for "loops_arithm_fp.dispatch.h"
  Enabled targets: VXE, VX, baseline
Generating multi-targets for "loops_arithmetic.dispatch.h"
  Enabled targets: VX, baseline
Generating multi-targets for "loops_comparison.dispatch.h"
  Enabled targets: VXE, VX, baseline
Generating multi-targets for "loops_exponent_log.dispatch.h"
  Enabled targets: baseline
Generating multi-targets for "loops_hyperbolic.dispatch.h"
  Enabled targets: VXE, VX, baseline
Generating multi-targets for "loops_logical.dispatch.h"
  Enabled targets: VX, baseline
Generating multi-targets for "loops_minmax.dispatch.h"
  Enabled targets: VXE, VX, baseline
Generating multi-targets for "loops_modulo.dispatch.h"
  Enabled targets: baseline
Generating multi-targets for "loops_trigonometric.dispatch.h"
  Enabled targets: VXE, baseline
Generating multi-targets for "loops_umath_fp.dispatch.h"
  Enabled targets: baseline
Generating multi-targets for "loops_unary.dispatch.h"
  Enabled targets: VXE, VX, baseline
Generating multi-targets for "loops_unary_fp.dispatch.h"
  Enabled targets: VXE, VX, baseline
Generating multi-targets for "loops_unary_fp_le.dispatch.h"
  Enabled targets: baseline
Generating multi-targets for "loops_unary_complex.dispatch.h"
  Enabled targets: VXE, VX, baseline
Generating multi-targets for "loops_autovec.dispatch.h"
  Enabled targets: VX, baseline
Generating multi-targets for "_simd.dispatch.h"
  Enabled targets: VX, VXE, baseline
Build targets in project: 84

NumPy 2.0.1

  User defined options
    Native files: /home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-id1eqrop/meson-python-native-file.ini
    buildtype   : release
    b_ndebug    : if-release
    b_vscrt     : md

Found ninja-1.11.1.git.kitware.jobserver-1 at /home/user/python/bin/ninja
+ /home/user/python/bin/ninja
[310/422] Compiling C object numpy/_core/libloops_autovec.dispatch.h_VX.a.p/meson-generated_loops_autovec.dispatch.c.o
FAILED: numpy/_core/libloops_autovec.dispatch.h_VX.a.p/meson-generated_loops_autovec.dispatch.c.o
gcc -Inumpy/_core/libloops_autovec.dispatch.h_VX.a.p -Inumpy/_core -I../numpy/_core -Inumpy/_core/include -I../numpy/_core/include -I../numpy/_core/src/common -I../numpy/_core/src/multiarray -I../numpy/_core/src/npymath -I../numpy/_core/src/umath -I/home/user/python/include/python3.12 -I/home/user/python/include -I/home/user/python/include/openssl -I/home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-id1eqrop/meson_cpu -fdiagnostics-color=always -DNDEBUG -Wall -Winvalid-pch -std=c11 -O3 -fno-strict-aliasing -fPIC -DNPY_INTERNAL_BUILD -DHAVE_NPY_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -O3 -DNPY_HAVE_VX -mzvector -march=arch11 -DNPY_MTARGETS_CURRENT=VX -MD -MQ numpy/_core/libloops_autovec.dispatch.h_VX.a.p/meson-generated_loops_autovec.dispatch.c.o -MF numpy/_core/libloops_autovec.dispatch.h_VX.a.p/meson-generated_loops_autovec.dispatch.c.o.d -o numpy/_core/libloops_autovec.dispatch.h_VX.a.p/meson-generated_loops_autovec.dispatch.c.o -c numpy/_core/libloops_autovec.dispatch.h_VX.a.p/loops_autovec.dispatch.c
during GIMPLE pass: vect
In file included from ../numpy/_core/src/common/npy_cpu_dispatch.h:41,
                 from ../numpy/_core/src/common/npy_config.h:5,
                 from ../numpy/_core/include/numpy/npy_common.h:10,
                 from ../numpy/_core/src/common/simd/simd.h:10,
                 from ../numpy/_core/src/umath/loops_autovec.dispatch.c.src:12:
../numpy/_core/src/umath/loops_autovec.dispatch.c.src: In function ‘LONG_bitwise_count_VX’:
../numpy/_core/src/umath/loops_autovec.dispatch.c.src:107:43: internal compiler error: Segmentation fault
 NPY_NO_EXPORT void NPY_CPU_DISPATCH_CURFX(@TYPE@_bitwise_count)
                                           ^~~~~~~~~~~~~~~~~~
/home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-id1eqrop/meson_cpu/npy_cpu_dispatch_config.h:40:30: note: in definition of macro ‘NPY__CPU_CAT__’
 #define NPY__CPU_CAT__(a, b) a ## b
                              ^
/home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-id1eqrop/meson_cpu/npy_cpu_dispatch_config.h:42:28: note: in expansion of macro ‘NPY__CPU_CAT_’
 #define NPY__CPU_CAT(a, b) NPY__CPU_CAT_(a, b)
                            ^~~~~~~~~~~~~
/home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-id1eqrop/meson_cpu/npy_cpu_dispatch_config.h:152:42: note: in expansion of macro ‘NPY__CPU_CAT’
     #define NPY_CPU_DISPATCH_CURFX(NAME) NPY__CPU_CAT(NPY__CPU_CAT(NAME, _), NPY_MTARGETS_CURRENT)
                                          ^~~~~~~~~~~~
/home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-id1eqrop/meson_cpu/npy_cpu_dispatch_config.h:41:29: note: in expansion of macro ‘NPY__CPU_CAT__’
 #define NPY__CPU_CAT_(a, b) NPY__CPU_CAT__(a, b)
                             ^~~~~~~~~~~~~~
/home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-id1eqrop/meson_cpu/npy_cpu_dispatch_config.h:42:28: note: in expansion of macro ‘NPY__CPU_CAT_’
 #define NPY__CPU_CAT(a, b) NPY__CPU_CAT_(a, b)
                            ^~~~~~~~~~~~~
/home/user/numpy/2.0.1/numpy-2.0.1/.mesonpy-id1eqrop/meson_cpu/npy_cpu_dispatch_config.h:152:55: note: in expansion of macro ‘NPY__CPU_CAT’
     #define NPY_CPU_DISPATCH_CURFX(NAME) NPY__CPU_CAT(NPY__CPU_CAT(NAME, _), NPY_MTARGETS_CURRENT)
                                                       ^~~~~~~~~~~~
../numpy/_core/src/umath/loops_autovec.dispatch.c.src:107:20: note: in expansion of macro ‘NPY_CPU_DISPATCH_CURFX’
 NPY_NO_EXPORT void NPY_CPU_DISPATCH_CURFX(@TYPE@_bitwise_count)
                    ^~~~~~~~~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Preprocessed source stored into /tmp/cc5etXAy.out file, please attach this to your bugreport.
```

### Python and NumPy Versions:

Python - 3.12.6
Numpy 2.0.1 and latest 2.1.3

**Comment by seberg** [comment]
Can you use a newer compiler version?  You may be able to get further if you disabling VX dispatching and maybe including it into the baseline (see https://numpy.org/doc/2.1/reference/simd/build-options.html#behaviors, I would have to look at it a bit longer to give an exact invocation, maybe someone else will give it).

The is an "internal compiler error".  Those should not happen for valid code.  I.e. whether or not the NumPy source contains something that makes this weird (or even slightly broken), the compiler probably needs to fix it.  But since this is a very old compiler, chances are it is already fixed.
(I remembr our `c.src` files generating somewhat broken things that caused internal compiler errors.  But I suspect this is at least not the identical issue, not sure though.)

We do run s390x on CI, so I don't know if there really is something that should be adjusted in our code.

**Comment by Ganeshkumhar1** [comment]
@seberg , could you please let me know exact invocation, I did try couple of steps but hitting same failure. I need to build it with gcc 8.4.1 only at this point. any help is appreciated.

**Comment by mattip** [comment]
See [the cpu feature build options](https://numpy.org/doc/stable/reference/simd/build-options.html#cpu-build-options). You can specifically tune the build for your CPU with `python -m build --wheel -Csetup-args=-Dcpu-baseline="native" -Csetup-args=-Dcpu-dispatch="none"` or specify specific features to avoid in the baseline and dispatch arguments.

**Comment by Ganeshkumhar1** [comment]
I tried all the combination but it is still failing .

bash-4.4$ python -m build --wheel -Csetup-args=-Dcpu-baseline="native" -Csetup-args=-Dcpu-dispatch="none"

* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - Cython>=3.0.6
  - meson-python>=0.15.0
* Getting build dependencies for wheel...
* Installing packages in isolated environment:
  - ninja >= 1.8.2
* Building wheel...
+ /tmp/build-env-44po4fju/bin/python /home/user/numpy/vendored-meson/meson/meson.py setup /home/user/numpy /home/user/numpy/.mesonpy-pgdttfjz -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Dcpu-baseline=native -Dcpu-dispatch=none --native-file=/home/user/numpy/.mesonpy-pgdttfjz/meson-python-native-file.ini
The Meson build system
Version: 1.5.2
Source dir: /home/user/numpy
Build dir: /home/user/numpy/.mesonpy-pgdttfjz
Build type: native build
Project name: NumPy
Project version: 2.0.1
C compiler for the host machine: gcc (gcc 8.4.1 "gcc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)")
C linker for the host machine: gcc ld.bfd 2.30-93
C++ compiler for the host machine: c++ (gcc 8.4.1 "c++ (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)")
C++ linker for the host machine: c++ ld.bfd 2.30-93
Cython compiler for the host machine: cython (cython 3.0.11)
Host machine cpu family: s390x
Host machine cpu: s390x
Program python found: YES (/tmp/build-env-44po4fju/bin/python)
Found pkg-config: YES (/bin/pkg-config) 1.4.2
Run-time dependency python found: YES 3.12
Has header "Python.h" with dependency python-3.12: YES 
Compiler for C supports arguments -fno-strict-aliasing: YES 
Test features "VX VXE VXE2" : Parial support, missing(VX VXE VXE2) 
Configuring npy_cpu_dispatch_config.h using configuration
Message: 
CPU Optimization Options
  baseline:
    Requested : native
    Enabled   : 
  dispatch:
    Requested : none
    Enabled   : 

Library m found: YES
Run-time dependency scipy-openblas found: NO (tried pkgconfig)
Run-time dependency openblas found: YES 0.3.27
Message: BLAS symbol suffix: 
Run-time dependency openblas found: YES 0.3.27
Program _build_utils/process_src_template.py found: YES (/tmp/build-env-44po4fju/bin/python /home/user/numpy/numpy/_build_utils/process_src_template.py)
Program _build_utils/tempita.py found: YES (/tmp/build-env-44po4fju/bin/python /home/user/numpy/numpy/_build_utils/tempita.py)
Configuring __config__.py using configuration
Checking for size of "short" : 2 
Checking for size of "int" : 4 
Checking for size of "long" : 8 
Checking for size of "long long" : 8 
Checking for size of "float" : 4 
Checking for size of "double" : 8 
Checking for size of "long double" : 16 
Checking for size of "size_t" : 8 
Checking for size of "size_t" : 8 (cached)
Checking for size of "wchar_t" : 4 
Checking for size of "off_t" : 8 
Checking for size of "Py_intptr_t" with dependency python-3.12: 8 
Checking for size of "PY_LONG_LONG" with dependency python-3.12: 8 
Has header "complex.h" : YES 
Checking for type "complex float" : YES 
Checking for size of "complex float" : 8 
Checking for type "complex double" : YES 
Checking for size of "complex double" : 16 
Checking for type "complex long double" : YES 
Checking for size of "complex long double" : 32 
Checking for function "sin" with dependency -lm: YES 
Checking for function "cos" with dependency -lm: YES 
Checking for function "tan" with dependency -lm: YES 
Checking for function "sinh" with dependency -lm: YES 
Checking for function "cosh" with dependency -lm: YES 
Checking for function "tanh" with dependency -lm: YES 
Checking for function "fabs" with dependency -lm: YES 
Checking for function "floor" with dependency -lm: YES 
Checking for function "ceil" with dependency -lm: YES 
Checking for function "sqrt" with dependency -lm: YES 
Checking for function "log10" with dependency -lm: YES 
Checking for function "log" with dependency -lm: YES 
Checking for function "exp" with dependency -lm: YES 
Checking for function "asin" with dependency -lm: YES 
Checking for function "acos" with dependency -lm: YES 
Checking for function "atan" with dependency -lm: YES 
Checking for function "fmod" with dependency -lm: YES 
Checking for function "modf" with dependency -lm: YES 
Checking for function "frexp" with dependency -lm: YES 
Checking for function "ldexp" with dependency -lm: YES 
Checking for function "expm1" with dependency -lm: YES 
Checking for function "log1p" with dependency -lm: YES 
Checking for function "acosh" with dependency -lm: YES 
Checking for function "asinh" with dependency -lm: YES 
Checking for function "atanh" with dependency -lm: YES 
Checking for function "rint" with dependency -lm: YES 
Checking for function "trunc" with dependency -lm: YES 
Checking for function "exp2" with dependency -lm: YES 
Checking for function "copysign" with dependency -lm: YES 
Checking for function "nextafter" with dependency -lm: YES 
Checking for function "cbrt" with dependency -lm: YES 
Checking for function "log2" with dependency -lm: YES 
Checking for function "pow" with dependency -lm: YES 
Checking for function "hypot" with dependency -lm: YES 
Checking for function "atan2" with dependency -lm: YES 
Checking for function "csin" with dependency -lm: YES 
Checking for function "csinh" with dependency -lm: YES 
Checking for function "ccos" with dependency -lm: YES 
Checking for function "ccosh" with dependency -lm: YES 
Checking for function "ctan" with dependency -lm: YES 
Checking for function "ctanh" with dependency -lm: YES 
Checking for function "creal" with dependency -lm: YES 
Checking for function "cimag" with dependency -lm: YES 
Checking for function "conj" with dependency -lm: YES 
Checking for function "strtoll" : YES 
Checking for function "strtoull" : YES 
Checking for function "cabs" with dependency -lm: YES 
Checking for function "cabsf" with dependency -lm: YES 
Checking for function "cabsl" with dependency -lm: YES 
Checking for function "cacos" with dependency -lm: YES 
Checking for function "cacosf" with dependency -lm: YES 
Checking for function "cacosl" with dependency -lm: YES 
Checking for function "cacosh" with dependency -lm: YES 
Checking for function "cacoshf" with dependency -lm: YES 
Checking for function "cacoshl" with dependency -lm: YES 
Checking for function "carg" with dependency -lm: YES 
Checking for function "cargf" with dependency -lm: YES 
Checking for function "cargl" with dependency -lm: YES 
Checking for function "casin" with dependency -lm: YES 
Checking for function "casinf" with dependency -lm: YES 
Checking for function "casinl" with dependency -lm: YES 
Checking for function "casinh" with dependency -lm: YES 
Checking for function "casinhf" with dependency -lm: YES 
Checking for function "casinhl" with dependency -lm: YES 
Checking for function "catan" with dependency -lm: YES 
Checking for function "catanf" with dependency -lm: YES 
Checking for function "catanl" with dependency -lm: YES 
Checking for function "catanh" with dependency -lm: YES 
Checking for function "catanhf" with dependency -lm: YES 
Checking for function "catanhl" with dependency -lm: YES 
Checking for function "cexp" with dependency -lm: YES 
Checking for function "cexpf" with dependency -lm: YES 
Checking for function "cexpl" with dependency -lm: YES 
Checking for function "clog" with dependency -lm: YES 
Checking for function "clogf" with dependency -lm: YES 
Checking for function "clogl" with dependency -lm: YES 
Checking for function "cpow" with dependency -lm: YES 
Checking for function "cpowf" with dependency -lm: YES 
Checking for function "cpowl" with dependency -lm: YES 
Checking for function "csqrt" with dependency -lm: YES 
Checking for function "csqrtf" with dependency -lm: YES 
Checking for function "csqrtl" with dependency -lm: YES 
Checking for function "csin" with dependency -lm: YES (cached)
Checking for function "csinf" with dependency -lm: YES 
Checking for function "csinl" with dependency -lm: YES 
Checking for function "csinh" with dependency -lm: YES (cached)
Checking for function "csinhf" with dependency -lm: YES 
Checking for function "csinhl" with dependency -lm: YES 
Checking for function "ccos" with dependency -lm: YES (cached)
Checking for function "ccosf" with dependency -lm: YES 
Checking for function "ccosl" with dependency -lm: YES 
Checking for function "ccosh" with dependency -lm: YES (cached)
Checking for function "ccoshf" with dependency -lm: YES 
Checking for function "ccoshl" with dependency -lm: YES 
Checking for function "ctan" with dependency -lm: YES (cached)
Checking for function "ctanf" with dependency -lm: YES 
Checking for function "ctanl" with dependency -lm: YES 
Checking for function "ctanh" with dependency -lm: YES (cached)
Checking for function "ctanhf" with dependency -lm: YES 
Checking for function "ctanhl" with dependency -lm: YES 
Checking for function "isfinite" with dependency -lm: YES 
Header "Python.h" has symbol "isfinite" with dependency python-3.12: YES 
Checking for function "isinf" with dependency -lm: YES 
Header "Python.h" has symbol "isinf" with dependency python-3.12: YES 
Checking for function "isnan" with dependency -lm: YES 
Header "Python.h" has symbol "isnan" with dependency python-3.12: YES 
Checking for function "signbit" with dependency -lm: YES 
Header "Python.h" has symbol "signbit" with dependency python-3.12: YES 
Checking for function "fallocate" : YES 
Header "Python.h" has symbol "HAVE_FTELLO" with dependency python-3.12: YES 
Header "Python.h" has symbol "HAVE_FSEEKO" with dependency python-3.12: YES 
Checking for function "backtrace" : YES 
Checking for function "madvise" : YES 
Has header "features.h" : YES 
Has header "xlocale.h" : NO 
Has header "dlfcn.h" : YES 
Has header "execinfo.h" : YES 
Has header "libunwind.h" : NO 
Has header "sys/mman.h" : YES 
Checking for function "strtold_l" : YES 
Compiler for C supports arguments -O3: YES 
Has header "endian.h" : YES 
Has header "sys/endian.h" : NO 
Compiler for C supports function attribute visibility:hidden: YES 
Configuring config.h using configuration
Configuring _numpyconfig.h using configuration
Configuring npymath.ini using configuration
Configuring mlib.ini using configuration
Configuring numpy.pc using configuration
Generating multi-targets for "_umath_tests.dispatch.h" 
  Enabled targets: baseline
Generating multi-targets for "argfunc.dispatch.h" 
  Enabled targets: baseline
Generating multi-targets for "x86_simd_argsort.dispatch.h" 
  Enabled targets: 
Generating multi-targets for "x86_simd_qsort.dispatch.h" 
  Enabled targets: 
Generating multi-targets for "x86_simd_qsort_16bit.dispatch.h" 
  Enabled targets: 
Generating multi-targets for "highway_qsort.dispatch.h" 
  Enabled targets: 
Generating multi-targets for "highway_qsort_16bit.dispatch.h" 
  Enabled targets: 
Generating multi-targets for "loops_arithm_fp.dispatch.h" 
  Enabled targets: baseline
Generating multi-targets for "loops_arithmetic.dispatch.h" 
  Enabled targets: baseline
Generating multi-targets for "loops_comparison.dispatch.h" 
  Enabled targets: baseline
Generating multi-targets for "loops_exponent_log.dispatch.h" 
  Enabled targets: baseline
Generating multi-targets for "loops_hyperbolic.dispatch.h" 
  Enabled targets: baseline
Generating multi-targets for "loops_logical.dispatch.h" 
  Enabled targets: baseline
Generating multi-targets for "loops_minmax.dispatch.h" 
  Enabled targets: baseline
Generating multi-targets for "loops_modulo.dispatch.h" 
  Enabled targets: baseline
Generating multi-targets for "loops_trigonometric.dispatch.h" 
  Enabled targets: baseline
Generating multi-targets for "loops_umath_fp.dispatch.h" 
  Enabled targets: baseline
Generating multi-targets for "loops_unary.dispatch.h" 
  Enabled targets: baseline
Generating multi-targets for "loops_unary_fp.dispatch.h" 
  Enabled targets: baseline
Generating multi-targets for "loops_unary_fp_le.dispatch.h" 
  Enabled targets: baseline
Generating multi-targets for "loops_unary_complex.dispatch.h" 
  Enabled targets: baseline
Generating multi-targets for "loops_autovec.dispatch.h" 
  Enabled targets: baseline
Generating multi-targets for "_simd.dispatch.h" 
  Enabled targets: baseline
Build targets in project: 61

NumPy 2.0.1

  User defined options
    Native files: /home/user/numpy/.mesonpy-pgdttfjz/meson-python-native-file.ini
    buildtype   : release
    b_ndebug    : if-release
    b_vscrt     : md
    cpu-baseline: native
    cpu-dispatch: none

Found ninja-1.11.1.git.kitware.jobserver-1 at /tmp/build-env-44po4fju/bin/ninja
+ /tmp/build-env-44po4fju/bin/ninja
[1/309] Generating numpy/generate-version with a custom command
Saving version to numpy/version.py
[250/309] Compiling C object numpy/_core/libloops_autovec.dispatch.h_baseline.a.p/meson-generated_loops_autovec.dispatch.c.o
FAILED: numpy/_core/libloops_autovec.dispatch.h_baseline.a.p/meson-generated_loops_autovec.dispatch.c.o 
gcc -Inumpy/_core/libloops_autovec.dispatch.h_baseline.a.p -Inumpy/_core -I../numpy/_core -Inumpy/_core/include -I../numpy/_core/include -I../numpy/_core/src/common -I../numpy/_core/src/multiarray -I../numpy/_core/src/npymath -I../numpy/_core/src/umath -I/tmp/1748780587/python/include/python3.12 -I/tmp/1748780587/python/include -I/tmp/1748780587/python/include/openssl -I/home/user/numpy/.mesonpy-pgdttfjz/meson_cpu -fdiagnostics-color=always -DNDEBUG -Wall -Winvalid-pch -std=c11 -O3 -fno-strict-aliasing -fPIC -DNPY_INTERNAL_BUILD -DHAVE_NPY_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -O3 -DNPY_MTARGETS_BASELINE -MD -MQ numpy/_core/libloops_autovec.dispatch.h_baseline.a.p/meson-generated_loops_autovec.dispatch.c.o -MF numpy/_core/libloops_autovec.dispatch.h_baseline.a.p/meson-generated_loops_autovec.dispatch.c.o.d -o numpy/_core/libloops_autovec.dispatch.h_baseline.a.p/meson-generated_loops_autovec.dispatch.c.o -c numpy/_core/libloops_autovec.dispatch.h_baseline.a.p/loops_autovec.dispatch.c
during GIMPLE pass: vect
In file included from ../numpy/_core/src/common/npy_cpu_dispatch.h:41,
                 from ../numpy/_core/src/common/npy_config.h:5,
                 from ../numpy/_core/include/numpy/npy_common.h:10,
                 from ../numpy/_core/src/common/simd/simd.h:10,
                 from ../numpy/_core/src/umath/loops_autovec.dispatch.c.src:12:
../numpy/_core/src/umath/loops_autovec.dispatch.c.src: In function ‘LONG_bitwise_count’:
../numpy/_core/src/umath/loops_autovec.dispatch.c.src:107:43: internal compiler error: Segmentation fault
 NPY_NO_EXPORT void NPY_CPU_DISPATCH_CURFX(@TYPE@_bitwise_count)
                                           ^~~~~~~~~~~~~~~~~~
/home/user/numpy/.mesonpy-pgdttfjz/meson_cpu/npy_cpu_dispatch_config.h:39:28: note: in definition of macro ‘NPY__CPU_EXPAND’
 #define NPY__CPU_EXPAND(X) X
                            ^
../numpy/_core/src/umath/loops_autovec.dispatch.c.src:107:20: note: in expansion of macro ‘NPY_CPU_DISPATCH_CURFX’
 NPY_NO_EXPORT void NPY_CPU_DISPATCH_CURFX(@TYPE@_bitwise_count)
                    ^~~~~~~~~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.

**Comment by seberg** [comment]
Well, I have one last try to offer, but beyond that I don't know how to help you further.  This is an a compiler bug surfacing on a 4 year old compiler version.  I had hoped it is just SIMD related, but maybe it is not, although I am not sure you tried disabling the `VX` completely, since `"native"` probably would have picked that up.

Maybe Matti has another suggestion.  I can only offer one thing to try.  The following diff should avoid the internal compiler error (ICE) that we saw previously on some GCC versions (8.something seems likely, but dunno):
```diff
diff --git a/numpy/distutils/conv_template.py b/numpy/distutils/conv_template.py
index c8933d1d42..3b5153a762 100644
--- a/numpy/distutils/conv_template.py
+++ b/numpy/distutils/conv_template.py
@@ -209,7 +209,7 @@ def parse_loop_header(loophead) :
 
 replace_re = re.compile(r"@(\w+)@")
 def parse_string(astr, env, level, line) :
-    lineno = "#line %d\n" % line
+    lineno = "\n"
 
     # local function for string replacement, uses env
     def replace(match):
@@ -285,7 +285,7 @@ def process_file(source):
         code = process_str(''.join(lines))
     except ValueError as e:
         raise ValueError('In "%s" loop at %s' % (sourcefile, e)) from None
-    return '#line 1 "%s"\n%s' % (sourcefile, code)
+    return '\n%s' % (sourcefile, code)
 
 
 def unique_key(adict):
```
It is completely harmless, the only thing that the diff breaks is making debugging parts of NumPy itself impossible.

**Comment by mattip** [comment]
In addition to what @seberg suggests, Try  `-Csetup-args=-Dcpu-baseline=""`. If that works, but is too slow add the optimizations `VSX`, `VSX2`, `VSX3` one at a time.

**Comment by kiruthikavaradarajan** [comment]
I am also facing the same issue when I install Numpy on RHEL 8.5 , any suggestions ?

            In file included from ../numpy/_core/src/common/npy_cpu_dispatch.h:41,
                             from ../numpy/_core/src/common/npy_config.h:5,
                             from ../numpy/_core/include/numpy/npy_common.h:10,
                             from ../numpy/_core/src/common/simd/simd.h:12,
                             from ../numpy/_core/src/umath/loops_autovec.dispatch.c.src:12:
            ../numpy/_core/src/umath/loops_autovec.dispatch.c.src: In function ‘LONG_bitwise_count’:
            ../numpy/_core/src/umath/loops_autovec.dispatch.c.src:107:43: internal compiler error: Segmentation fault
             NPY_NO_EXPORT void NPY_CPU_DISPATCH_CURFX(@TYPE@_bitwise_count)
                                                       ^~~~~~~~~~~~~~~~~~
            /tmp/pip-install-ev8fqtxh/numpy_8cbf4b63961f4c908aca734ad9d3dc22/.mesonpy-6o60btoi/meson_cpu/npy_cpu_dispatch_config.h:39:28: note: in definition of macro ‘NPY__CPU_EXPAND’
             #define NPY__CPU_EXPAND(X) X
                                        ^
            ../numpy/_core/src/umath/loops_autovec.dispatch.c.src:107:20: note: in expansion of macro ‘NPY_CPU_DISPATCH_CURFX’
             NPY_NO_EXPORT void NPY_CPU_DISPATCH_CURFX(@TYPE@_bitwise_count)
                                ^~~~~~~~~~~~~~~~~~~~~~
            Please submit a full bug report,
            with preprocessed source if appropriate.
            See <http://bugzilla.redhat.com/bugzilla> for instructions.
            Preprocessed source stored into /tmp/ccsoFHMj.out file, please attach this to your bugreport.
            [340/354] Compiling C object numpy/random/_bounded_integers.cpython-311-powerpc64le-linux-gnu.so.p/meson-generated_numpy_random__bounded_integers.pyx.c.o
            [341/354] Compiling C object numpy/linalg/_umath_linalg.cpython-311-powerpc64le-linux-gnu.so.p/lapack_lite_f2c_s_lapack.c.o
            [342/354] Compiling C object numpy/random/bit_generator.cpython-311-powerpc64le-linux-gnu.so.p/meson-generated_numpy_random_bit_generator.pyx.c.o
            [343/354] Compiling C++ object numpy/fft/_pocketfft_umath.cpython-311-powerpc64le-linux-gnu.so.p/_pocketfft_umath.cpp.o
            In file included from ../numpy/fft/_pocketfft_umath.cpp:24:
            ../numpy/fft/pocketfft/pocketfft_hdronly.h: In function ‘void pocketfft::detail::PM(T&, T&, T, T) [with T = pocketfft::detail::cmplx<long double>]’:
            ../numpy/fft/pocketfft/pocketfft_hdronly.h:27

**Comment by seberg** [comment]
> any suggestions ?

Not beyond what was already said.  What did you try?

**Comment by th0ma7** [comment]
I investigated a little more:
- using gcc-8.5, glibc-2.26 (synology DSM-7.1 toolchain) it fails on all 2.x version, success on 1.26.4
- using gcc-12.2, glibc-2.36 (synology DSM-7.2 toolchain) success on both version 2.x and 1.26.4

So clearly there is an association with the compiler version.  Although I'd appreciate a workaround that as I have to keep maintaining DSM-7.1 using gcc-8.5 - there may be some flags I could pass along to avoid this?

So i looked a little further and tested `-fno-tree-vectorize` which sucesfully worked!  So I then tested `-fno-tree-loop-vectorize` which also worked and is less impactfull on optimizations.

All in all, got a working solution with gcc-8.x using  `-fno-tree-loop-vectorize` CFLAG - hopefuly that can help someone else 🚀

**Comment by th0ma7** [comment]
I ended-up re-hitting this issue when openblas librarires are in the library path, thus detected.  I tried re-disabling it using meson options, but nothing worked.

In the end I disable optimizations on that specific definition and it finally solved the issue:
```
--- numpy/_core/src/umath/loops_autovec.dispatch.c.src-orig     2025-02-12 20:45:32.000000000 +0000
+++ numpy/_core/src/umath/loops_autovec.dispatch.c.src  2025-03-01 14:13:16.583835435 +0000
@@ -104,11 +104,13 @@ NPY_NO_EXPORT void NPY_CPU_DISPATCH_CURF
 #endif
 }
 
+#pragma GCC optimize ("0")  // Deactivate optimisations
 NPY_NO_EXPORT void NPY_CPU_DISPATCH_CURFX(@TYPE@_bitwise_count)
 (char **args, npy_intp const *dimensions, npy_intp const *steps, void *NPY_UNUSED(func))
 {
     UNARY_LOOP_FAST(@type@, npy_ubyte, *out = npy_popcount@c@(in));
 }
+#pragma GCC reset_options  // Re-activate optimisations
 
 /**end repeat**/

```

A suggested permanent fix would be to detect said gcc known to segfault and appy this optimization removal only then.

My PR for the synocommunity project is https://github.com/SynoCommunity/spksrc/pull/6454 and I'll be commiting my updated code shortly which includes said patch if that can help anyone.

**Comment by seberg** [comment]
Disabling optimizations completely seems a big hammer that is potentially very noticeable speed wise.
Adding that `-fno-tree-loop-vectorize` (maybe as a pragma?), would seem better.  FWIW, I suppose if it is specific to a compiler version + platform, we could probably merge it into NumPy also.

**Comment by hgy59** [comment]
> Disabling optimizations completely seems a big hammer that is potentially very noticeable speed wise.

The patch by @th0ma7 does not completely disable optimization, it disables optimization for the specific function only:

```patch
--- numpy/_core/src/umath/loops_autovec.dispatch.c.src-orig	2025-02-12 20:45:32.000000000 +0000
+++ numpy/_core/src/umath/loops_autovec.dispatch.c.src	2025-03-01 14:13:16.583835435 +0000
@@ -104,11 +104,13 @@ NPY_NO_EXPORT void NPY_CPU_DISPATCH_CURF
 #endif
 }
 
+#pragma GCC optimize ("0")  // Deactivate optimisations
 NPY_NO_EXPORT void NPY_CPU_DISPATCH_CURFX(@TYPE@_bitwise_count)
 (char **args, npy_intp const *dimensions, npy_intp const *steps, void *NPY_UNUSED(func))
 {
     UNARY_LOOP_FAST(@type@, npy_ubyte, *out = npy_popcount@c@(in));
 }
+#pragma GCC reset_options  // Re-activate optimisations
 
 /**end repeat**/
 
```
