### ISSUE TITLE
numpy.mean is *extremely* inaccurate for large float32 arrays

### ISSUE THREAD

**Issue by capybaralet** [numpy/numpy#5681]
I know it says in the docs it can be inaccurate, but I had no idea it was this bad.  Maybe this should be the example given?

In [37]: np.mean(np.random.binomial(1,.5,(100000,5000)).astype('float32'))
Out[37]: 0.033554431

**Comment by charris** [comment]
I get
```
In [1]:  np.mean(np.random.binomial(1,.5,(100000,5000)).astype('float32'))
Out[1]: 0.50007874
```
What numpy version are you using? You might also want to look at the `dtype` keyword.

**Comment by capybaralet** [comment]
1.8.0

What would I be looking for in the dtype?  and shouldn't it just be float32, since I cast it to that?

**Comment by charris** [comment]
No, in a case like this `dtype=np.float64` would accumulate results with more precision. The np.sum function was improved in 1.9 for contiguous data, which is why I get better results.

**Comment by capybaralet** [comment]
Yes, I'm aware that float64 gives more precision, but I didn't realize the difference could be this bad.  I'm glad to see it is fixed in newer versions.

**Comment by ewmoore** [comment]
The dtype keyword hint is suggesting that you pass your float32 array in,
but specify the dtype keyword to do the accumulation in the higher
precision type. Numpy will do this without force casting a copy of the full
array in the new dtype, so excess memory use won't be a problem, but you'll
still get the higher precision result.

**Comment by charris** [comment]
Closing this now.
