### ISSUE TITLE
minor doc typos: titles for r_, c_, s_, ix_ miss the final underscore

### ISSUE THREAD

**Issue by anntzer** [numpy/numpy#6769]
See e.g. http://docs.scipy.org/doc/numpy/reference/generated/numpy.ix_.html
I mean the "big" title, not the one that shows the call signature.

**Comment by gfyoung** [comment]
Just curious, where is the code that generates the online documentation?  Seems like it should be a relatively easy fix, right?

**Comment by eric-wieser** [comment]
This is presumably actually a bug in numpy/numpydoc?

**Comment by eric-wieser** [comment]
Perhaps this is https://github.com/sphinx-doc/sphinx/issues/519?

**Comment by eric-wieser** [comment]
Hopefully fixed by https://github.com/sphinx-doc/sphinx/pull/3581

**Comment by pv** [comment]
Probably numpydoc bug, I think the sphinx params stuff is not used.

**Comment by eric-wieser** [comment]
@pv: Yep, the issue was actually in `apidoc`, which I assume is used?

How would I go about testing if the above fix corrected the problem? Is building numpy docs easy?

**Comment by MSeifert04** [comment]
It depends, I got it to work locally on windows but with my installation the issue isn't fixed yet. But I'm not sure what locally installed packages might interfere with the way I build the documentation (on windows I use `sphinx_build`)

**Comment by charris** [comment]
> Is building numpy docs easy?

Depends. On linux it is pretty easy once you are set up with all the correct software and latex styles, but getting there can be a pain. After that `paver pdf` will create the pdf docs or you can change to `doc/` and follow the instructions in `HOWTO_BUILD_DOCS.rst.txt`.

**Comment by pv** [comment]
`apt-get install --install-suggests python-sphinx`

**Comment by charris** [comment]
Note that paver documents the installed numpy whereas using the makefile builds numpy in a virtual enviroment and documents that, so probably the preferable way to go.

**Comment by eric-wieser** [comment]
sphinx-doc/sphinx#3581 does not fix this issue. The problem lies in the use of Jinja templates to geneterate RST within `sphinx.ext.autosummary`, and it's difficult to see at what level things should be escaped

**Comment by eric-wieser** [comment]
I've confirmed that:
* This bug is still present on Sphinx `stable`
* This is fixed by https://github.com/sphinx-doc/sphinx/pull/3585

**Comment by eric-wieser** [comment]
> whereas using the makefile builds numpy in a virtual enviroment and documents that

I don't agree with that -`HOWTO_BUILD_DOCS.rst.txt` says:

> Since large parts of the main documentation are stored in
> docstrings, you will need to first build NumPy, and install it so
> that the correct version is imported by
> 
>     >>> import numpy
> 
> Note that you can eg. install NumPy to a temporary location and set
> the PYTHONPATH environment variable appropriately.

**Comment by charris** [comment]
I think `HOWTO_BUILD_DOCS.rst.txt` is out of date. It worked last time I did `make dist`.

**Comment by charris** [comment]
Hmm, that means that paver should also be updated the use `make dist`.

**Comment by eric-wieser** [comment]
Ah, I thought you were telling me to run `make html` in `doc`

**Comment by eric-wieser** [comment]
This won't actually be fixed unless we start building docs with sphinx 1.5.4 - and right now, we're using 1.2.3

**Comment by charris** [comment]
@eric-wieser I don't currently generate the uploaded documentation, I ask  @rgommers to do it. Ralf, what sphinx version do you use?

**Comment by charris** [comment]
Probably need to update `HOWTO_BUILD_DOCS.rst.txt` with the minimum sphinx version among other things.

**Comment by eric-wieser** [comment]
Or maybe even add a `requirements.txt` in there, in case we need any sphinx extensions in future

**Comment by eric-wieser** [comment]
Looks like we're now using sphinx 1.6.6, so this is fixed
